import json

translations = {
  "that's still good for tonight what time": "eso sigue en pie para esta noche, ¿a qué hora?",
  "nope we need to roll a joint": "no, tenemos que armar un porro",
  "cool I'm on my way to the gym now let's touch base later": "genial, voy camino al gimnasio ahora, hablamos luego",
  "yes this is your lucky night": "sí, es tu noche de suerte",
  "hey I'm a good girl lull": "oye soy una niña buena jajaja",
  "I'm only looking for paper meets honest like you pay me if we fought": "solo busco citas pagadas para ser honesta, tipo que me pagas si cogemos",
  "only with hot guys": "solo con chicos atractivos",
  "getting ready now should be there 12:30 is that okay I'll live blah blah blah like 20 minutes away but there's traffic": "alistándome ahora, debería llegar 12:30 ¿está bien? vivo bla bla bla a unos 20 minutos de ahí pero hay tráfico",
  "what are you doing tomorrow night": "¿qué harás mañana por la noche?",
  "is that weird I'm actually a stripper just started escort my friend told me that": "¿es eso raro? en realidad soy stripper, recién empecé de escort, mi amiga me recomendó eso",
  "this is going to be fun": "esto va a ser divertido",
  "okay how is your day it's birthday today along my friends threw me a party I'm on ecstasy": "ok ¿qué tal tu día? hoy es mi cumpleaños, mis amigos me hicieron una fiesta, estoy en éxtasis",
  "hey wanna cuddle and f***": "oye, ¿quieres que nos abracemos y cojamos?",
  "law you want to date me I don't blame you I'm awesome": "jajaja quieres salir conmigo, no te culpo, soy increíble",
  "hey what's up": "oye ¿qué onda?",
  "thanks but don't worry I'm Way too dominant in bed for that": "gracias pero no te preocupes, soy demasiado dominante en la cama para eso",
  "okay I'm down": "ok, me apunto",
  "okay": "ok",
  "and you think telling me a few hours for a day that you only want to meet for money it's gonna make me want to date you": "¿y crees que diciéndome a unas horas de nuestra cita que solo quieres verte por dinero me va a dar ganas de salir contigo?",
  "oh stop we both know you got nice booty": "oh basta, ambos sabemos que tienes buen trasero",
  "come to mr. Joe": "ven a mr. Joe",
  "I'm going out": "voy a salir",
  "??": "??",
  "can't tomorrow sorry oh well": "no puedo mañana, lo siento, ni modo",
  "go into mr. homn Jones": "yendo a mr. Jones",
  "yes well I work now leaving for": "sí, bueno, trabajo ahora, saliendo para allá",
  "what kind of plans": "¿qué tipo de planes?",
  "is this an interrogation": "¿es un interrogatorio?",
  "okay so you can't hang out tomorrow aren't you going out with a girl tonight whatever law": "ok, entonces no puedes salir mañana, ¿acaso no vas a salir con una chica esta noche? lo que sea jajaja",
  "I'm free day time I worked those nights": "estoy libre de día, trabajo en las noches",
  "sorry": "lo siento",
  "how long it's kind of clear you're an amateur a pro wouldn't use tinder for this": "¿hace cuánto? es un poco claro que eres amateur, una pro no usaría Tinder para esto",
  "I love the club": "me encanta el club",
  "we should definitely get together sometime soon": "definitivamente deberíamos juntarnos pronto",
  "typical Miami brat": "típica niña mimada de Miami",
  "you can come over": "puedes venir a mi casa",
  "so cute": "qué lindo",
  "oh": "oh",
  "okay be there soon": "ok, llegaré pronto",
  "okay cool good thing you're awake oh my god I hate dildo well I can't wait I'm so excited": "ok genial, menos mal que estás despierto oh dios mío odio los consoladores bueno no puedo esperar estoy muy emocionada",
  "didn't you flake on me an hour ago sorry": "¿no me cancelaste hace una hora? lo siento",
  "Sunday at leave 4:30 I could go then I don't know it depends how busy the restaurant is": "el domingo a las 4:30 podría ir, no sé, depende de qué tan ocupado esté el restaurante",
  "you free Thursday Friday night": "¿estás libre jueves o viernes por la noche?",
  "it's lit I'm going home boring single low": "está prendido, me voy a casa, aburrida soltera jajaja",
  "of course": "por supuesto",
  "I like that as long as I get to ride you it's all good": "me gusta eso, siempre que pueda montarte todo está bien",
  "hey you still awake": "oye, ¿todavía estás despierto?",
  "plans tonight and we made plans for tomorrow": "planes esta noche y ya hicimos planes para mañana",
  "well I'm out of luck I'm skinny": "bueno, no tengo suerte, soy delgada",
  "so give me the basics tattoos kids funk inks": "entonces dame lo básico, tatuajes, hijos, cosas raras",
  "yes well": "sí, bueno",
  "a girl ?": "¿una chica?",
  "I'm in the car now leaving my friend's house I'm almost home 12:05 now goal of Brahma Baba perfect": "estoy en el auto ahora, saliendo de la casa de mi amiga, ya casi llego a casa 12:05 ahora bla bla bla perfecto",
  "oh me too \ud83d\ude09": "oh yo también \ud83d\ude09",
  "okay I will": "ok lo haré",
  "what's your address": "¿cuál es tu dirección?",
  "oh thank you baby you're so sweet I'm not brat actually but thanks low": "oh gracias bebé eres muy dulce, en realidad no soy mimada pero gracias jajaja",
  "why are you being aggressive like that I'm hanging out with my buddy tonight we made plans tomorrow": "¿por qué estás tan agresiva? voy a salir con mi amigo esta noche, tenemos planes mañana",
  "well is this the right place": "bueno, ¿es este el lugar correcto?",
  "no law": "no jajaja",
  "2.5 stars law": "2.5 estrellas jajaja",
  "get in the car and come on over then": "súbete al auto y ven para acá entonces",
  "my friend's birthday is today all how convenient going to that we can roll tomorrow": "hoy es el cumpleaños de mi amiga, qué conveniente, iré a eso así que podemos salir mañana",
  "plans tonight I'll see you tomorrow evening": "tengo planes esta noche, te veré mañana por la tarde-noche",
  "what time should I expect you": "¿a qué hora te espero?",
  "yo sexy": "oye sexy",
  "to hang out": "para pasar el rato",
  "busy text you later": "ocupada, te escribo luego",
  "[Mi direcci\u00f3n]": "[Mi dirección]",
  "the one who likes the booty": "al que le gusta el trasero",
  "well you're definitely losing points right now one of these life goes on blah blah blah": "bueno, definitivamente estás perdiendo puntos ahora mismo, la vida sigue, bla bla bla",
  "I can imagine I'll be free a bit later tomorrow night you should go by for a drink or two": "me imagino, estaré libre un poco más tarde mañana por la noche, deberías pasar por un trago o dos",
  "at the salon now going blonde law while caramel": "en el salón de belleza ahora, poniéndome rubia jajaja bueno caramelo",
  "are you waste with jdj and whatever some nonsense": "¿estás borracho con jdj o lo que sea, alguna tontería?",
  "my balcony is open tequila and wine on tap": "mi balcón está abierto, tequila y vino de barril",
  "I don't really like f***ing a lot so people I'm asking not escort so just dude sometimes when I'm bored kind of thing I like being with one person": "en realidad no me gusta coger mucho con gente, así que no soy escort solo con algún tipo a veces cuando estoy aburrida ese tipo de cosas, me gusta estar con una sola persona",
  "fake that attitude right idea if you quit making excuses I'm just out here in the world doing my thing": "finge esa actitud, buena idea, si dejas de poner excusas yo solo estoy aquí en el mundo haciendo lo mío",
  "well I don't do it a lot that's why": "bueno, no lo hago mucho, por eso",
  "to mr. Jones come with me": "a mr. Jones ven conmigo",
  "lame": "aburrido",
  "text me": "escríbeme",
  "finishing up a video what's up": "terminando un video, ¿qué onda?",
  "lo a nightclub": "jajaja un club nocturno",
  "I probably do somewhere": "probablemente tengo por ahí",
  "I'm gonna make you swallow every inch": "voy a hacer que te tragues cada centímetro",
  "yes see you then": "sí, nos vemos entonces",
  "well sorry": "bueno, lo siento",
  "sorry busy with my son it's his birthday": "lo siento, ocupada con mi hijo, es su cumpleaños",
  "a night club was boring yes especially that one I hate all clubs": "un club nocturno era aburrido sí, especialmente ese, odio todos los clubes",
  "from tinder": "de Tinder",
  "ah a Florida girl": "ah una chica de Florida",
  "no I've dated a few strippers your approach is weird though": "no, he salido con algunas strippers pero tu enfoque es raro",
  "okay cool do you want me to bring weed do you smoke": "ok genial ¿quieres que lleve marihuana, fumas?",
  "yes": "sí",
  "thanks": "gracias",
  "you have a bong weed we can smoke": "¿tienes un bong o marihuana que podamos fumar?",
  "you thought about that one for a while": "lo pensaste por un rato",
  "how's 9:30": "¿qué tal las 9:30?",
  "hey trouble": "hola problema",
  "all right let's do Sunday evening then okay": "muy bien, hagamos el domingo por la tarde-noche entonces ¿ok?",
  "well": "bueno",
  "no well": "no, bueno",
  "the ugly ones you f*** for free": "¿con los feos coges gratis?",
  "who's Jones": "¿quién es Jones?",
  "what do you want to do let's just hang out tomorrow nothing open": "¿qué quieres hacer? solo salgamos mañana, no hay nada abierto",
  "hey": "hola",
  "want to come to mr. Jones with me": "¿quieres venir a mr. Jones conmigo?",
  "sounds boring I'll pass": "suena aburrido, paso",
  "okay cool anything to smoke out of": "ok genial ¿tienes algo en qué fumar?",
  "so now all I want is to choke on a nice dick I hope your dick is nice": "así que ahora todo lo que quiero es ahogarme con una buena verga, espero que tu verga sea buena",
  "say 9:00 okay": "digamos a las 9:00 ok",
  "come to mr. Alex": "ven a mr. Alex",
  "I'm five five and little ass lump not true": "mido 5'5 y no tengo mucho trasero, no es verdad",
  "can we put on music": "¿podemos poner música?",
  "my favorite thanks love": "mi favorito, gracias amor",
  "can I ride you": "¿puedo montarte?",
  "I don't pay for sex and that's what you wanted you should have just said so in the beginning": "no pago por sexo y eso es lo que querías, deberías haberlo dicho desde el principio",
  "that's better are you from here originally": "eso está mejor, ¿eres de aquí originalmente?",
  "on special occasions but bring it might be fun": "en ocasiones especiales, pero tráela, podría ser divertido",
  "hi": "hola",
  "I'm at the gym right now what's up": "estoy en el gimnasio ahora, ¿qué onda?",
  "you only meet people for money": "¿solo conoces gente por dinero?",
  "[Mi nombre]": "[Mi nombre]",
  "is this your apology gift": "¿este es tu regalo de disculpa?",
  "of course especially with that ass": "por supuesto, especialmente con ese trasero",
  "what are you doing tonight want to go to komodo with me I'm going with some friends": "¿qué harás esta noche? ¿quieres ir a Komodo conmigo? iré con unos amigos",
  "why can't you go tonight": "¿por qué no puedes ir esta noche?",
  "for my body size yes I do thank you": "para mi tamaño de cuerpo sí lo tengo, gracias",
  "what are you doing ?": "¿qué estás haciendo?",
  "I work during the day what time do you finish work usually": "trabajo de día, ¿a qué hora terminas de trabajar usualmente?",
  "it will be send me a tease my pussy's super wet already": "lo será, mándame una provocación, mi coño ya está súper mojado",
  "you're a good girl all that sucks I think you look better as a boy": "eres una niña buena, todo eso apesta, creo que te ves mejor como chico",
  "oh you're a MILF": "oh, eres una MILF",
  "oh you're an escort": "oh, eres una escort"
}

file_path = "c:\\desarrollos\\antigravity\\text game youtube estudio ejemplos\\parsed_cases\\wCi7ExnudpU.json"

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# The instructions say: "Traduce los campos 't' (texto del mensaje) y 'desc' o 'title' si están en inglés."
# In this specific file, the message texts are in 'texto', and the video_id is 'wCi7ExnudpU' 
# there isn't a 'title' or 'desc', but there is 'justificacion_scoring' which is already in Spanish.
# Let's traverse all messages and update 'texto'
# We will use the original format and just replace the known English strings.

for fase in data.get("fases", []):
    for msg in fase.get("mensajes", []):
        if msg.get("texto") in translations:
            msg["texto"] = translations[msg["texto"]]

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Translation successful.")
